name: estacionamento
description: Estacionamento do Sr. João
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  either_dart: ^0.1.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  get: ^4.6.1
  get_storage: ^2.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

flutter:
  uses-material-design: true